version: '2'
services:
  packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    depends_on:
      - helium-miner
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./reset.sh:/app/reset.sh.gpiod
    environment:
      - MODEL=RAK2287
      - INTERFACE=SPI
      - DEVICE=/dev/spidev0.0
      - RESET_GPIO=17
      - GPIO_CHIP=gpiochip0
      - POWER_EN_GPIO=18
      - POWER_EN_LOGIC=1
      - HAS_GPS=0
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=1680
  helium-miner:
    build: ./hm-gatewayrs
    privileged: true
    network_mode: host
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: on-failure
    environment:
      - RELEASE_BUMPER=foobar5
      - FIRMWARE_VERSION=v1.0.0-alpha.21
    labels:
      io.balena.features.balena-api: '1'
volumes:
  miner-storage:
  miner-log:
